services:
  # FastAPI Backend Service
  api:
    build: .
    container_name: csv-doc-analyst-api
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX=${PINECONE_INDEX_NAME}
      - PINECONE_ENV=${PINECONE_ENV}
      - PINECONE_NAMESPACE=${PINECONE_NAMESPACE}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_LOCATION=${GCP_LOCATION}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./data:/app/data
      - ./secrets:/app/secrets
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Streamlit Frontend Service
  frontend:
    build: .
    container_name: csv-doc-analyst-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    command: ["streamlit", "run", "app/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  data:
  secrets:

networks:
  default:
    name: csv-doc-analyst-network
